export const Login_Api="https://ample-grouse-clearly.ngrok-free.app/auth/login" 
export const Signup_api="https://ample-grouse-clearly.ngrok-free.app/auth/signup"
export const Chat_api='https://ample-grouse-clearly.ngrok-free.app/chatbot/chat' 
export const clear_chat_api='https://ample-grouse-clearly.ngrok-free.app/chatbot/clear_history'
export const pdf_upload_api="https://suitable-jolly-falcon.ngrok-free.app/upload"
export const ask_pdf="https://suitable-jolly-falcon.ngrok-free.app/ask_pdf"
export const ask_csv="https://suitable-jolly-falcon.ngrok-free.app/ask_csv"
export const ask_user_details="https://ample-grouse-clearly.ngrok-free.app/user/get_subscription"
export const Transcript_api = "https://ample-grouse-clearly.ngrok-free.app/audio/transcript"
export const Voice_api = "https://ample-grouse-clearly.ngrok-free.app/audio/voice"
export const translate_api='https://ample-grouse-clearly.ngrok-free.app/chatbot/translate'